#!/bin/bash

# MIT license
#
# Copyright (c) 2020 Manish Sahani
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

__KSH_CACHE="$HOME/.cache/kalkayan_sh/"

function __ksh_get_cached_path () {
    echo "$__KSH_CACHE/${1#*://}"
}

function __ksh_test_and_cache () {
    [[ -f "$(__ksh_get_cached_path "$1")" ]] || \
        /usr/bin/curl "$1" -o "$(__ksh_get_cached_path "$1")" --create-dirs
}

function import () {
    mkdir -p $__KSH_CACHE && __ksh_test_and_cache "$1" && \
        source "$(__ksh_get_cached_path "$1")"
}
